name: CI
on:
  workflow_dispatch:
  pull_request:
jobs:
   format:
     name: Format
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v3
         with:
           ref: ${{ github.head_ref }}
       - name: Read Go version
         run: echo "GO_VERSION=$(cat ./.go-version)" >> $GITHUB_ENV
       - name: set up go
         uses: actions/setup-go@v4
         with:
           go-version: ${{ env.GO_VERSION }}
       - name: Format code
         run: make fmt
       - name: Auto commit
         uses: stefanzweifel/git-auto-commit-action@v4
         with:
           commit_message: "Apply Code formatter changes"
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=./.golangci.yml ./..."
          fail_on_error: true
          reporter: "github-pr-review"